[package]
name = "chrono-persian"
version = "0.1.0"
edition = "2021"
authors = ["mralisalehi"]
description = "simple wrapper around chrono for persian(jalali) dates"
license = "MIT"


[dependencies]
chrono = "0.4"